[package]
authors = ["Jorge Aparicio <jorge@japaric.io>", "William D. Jones <thor0505@comcast.net>"]
edition = "2018"
name = "msp430-quickstart"
version = "0.2.0"

[dependencies]
msp430 = "0.2.0"
msp430-rt = "0.2.0"
panic-msp430 = "0.2.0"

# [dependencies.msp430-rtfm]
# git = "https://github.com/japaric/msp430-rtfm"

[dependencies.msp430g2553]
version = "0.2.0"
features = ["rt"]

[dependencies.once_cell]
version = "1.2.0"
default_features = false

[profile.release]
lto = true

[features]
unsafe = []
